version: 1.0.{build}

branches:
  only:
  - community
  
image: Visual Studio 2017

configuration: 
  - Debug
  - Release
  
platform:
  - x64
  - x86
  
build:
  project: grade-scores.sln
  verbosity: normal
  
artifacts:
- path: {$platform}\{configuration}\grade-scores.exe
  name: {platform}_{configuration}_grade-scores
- path: {platform}\{configuration}\grade-scores.exe
  name: {platform}_{configuration}_grade-scores
- path: {configuration}\grade-scores.exe
  name: {platform}_{configuration}_grade-scores
- path: {configuration}\grade-scores.exe
  name: {platform}_{configuration}_grade-scores
- path: students.txt
  name: students.txt