version: 1.0.{build}
branches:
  only:
  - community
image: Visual Studio 2017
configuration: 
  - Debug
  - Release
platform:
  - x64
  - x86
build:
  verbosity: normal
artifacts:
- path: x64\Release\grade-scores.exe
  name: x64\Release\grade-scores.exe
- path: x64\Debug\grade-scores.exe
  name: x64\Debug\grade-scores.exe
- path: Release\grade-scores.exe
  name: x86\Release\grade-scores.exe
- path: Debug\grade-scores.exe
  name: x86\Debug\grade-scores.exe
- path: students.txt
  name: students.txt