version: 1.0.{build}

branches:
  only:
  - community
  
image: Visual Studio 2017

configuration: 
  - Debug
  - Release
  
platform:
  - x64
  - x86
  
build:
  project: grade-scores.sln
  verbosity: normal
  
artifacts:
- path: x64\Release
  name: grade-scores.exe
- path: x64\Debug
  name: grade-scores.exe
- path: Release
  name: grade-scores.exe
- path: Debug
  name: grade-scores.exe
- path: students.txt
  name: students.txt