version: 1.0.{build}

branches:
  only:
  - community
  
image: Visual Studio 2017

configuration: 
  - Debug
  - Release
  
platform:
  - x64
  - x86
  
build:
  project: grade-scores.sln
  verbosity: normal
  
artifacts:
- path: X64\Debug\grade-scores.exe
  name: X64_Debug_$configuration_grade-scores
- path: X64\Release\grade-scores.exe
  name: X64_Release_grade-scores
- path: Debug\grade-scores.exe
  name: x86_Debug_grade-scores
- path: Release\grade-scores.exe
  name: x86_Release_grade-scores
- path: students.txt
  name: students.txt